In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats

In [2]:
order=pd.read_csv("CostomerOrderForm.csv")
order.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [3]:
order4=order['Phillippines'].value_counts()
order4

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [4]:
order4.Error Free

SyntaxError: invalid syntax (<ipython-input-4-594c6ebb124f>, line 1)

In [12]:
order1=order['Indonesia'].value_counts()
order1

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [16]:
order2=order['Malta'].value_counts()
order2

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [17]:
order3=order['India'].value_counts()
order3

Error Free    280
Defective      20
Name: India, dtype: int64

In [21]:
order4.values,order1.values,order2.values,order3.values
val1

(array([271,  29], dtype=int64),
 array([267,  33], dtype=int64),
 array([269,  31], dtype=int64),
 array([280,  20], dtype=int64))

In [23]:
observed_values=order4.values,order1.values,order2.values,order3.values
print("observed_values:-\n",observed_values)

observed_values:-
 (array([271,  29], dtype=int64), array([267,  33], dtype=int64), array([269,  31], dtype=int64), array([280,  20], dtype=int64))


In [28]:
val1=stats.chi2_contingency(order4.values)
val1

(0.0, 1.0, 0, array([271.,  29.]))

In [29]:
val2=stats.chi2_contingency(order1.values)
val2

(0.0, 1.0, 0, array([267.,  33.]))

In [30]:
val3=stats.chi2_contingency(order2.values)
val3

(0.0, 1.0, 0, array([269.,  31.]))

In [41]:
val4=stats.chi2_contingency(order3.values)
val4

(0.0, 1.0, 0, array([280.,  20.]))

In [43]:
array=order1.values
array

array([267,  33], dtype=int64)